"use client";

import { BadgeCheck, ChevronDown, ChevronUp, MapPinned, Pencil, Plus, Route, Save, ShieldCheck, Sparkles, Trash2, X } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import type { JourneyPurposeCard } from "@/lib/content";

const icons = { ShieldCheck, MapPinned, Sparkles, Route, BadgeCheck };
type AdminCard = JourneyPurposeCard & { id: number };

async function request<T>(url: string, options?: RequestInit) { const response = await fetch(url, options); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "Something went wrong."); return body as T; }

const emptyCard: JourneyPurposeCard = { title: "", description: "", icon: "Route", buttonText: "Explore journey", destinationUrl: "/packages", linkType: "internal", openInNewTab: false, displayOrder: 1, active: true };

export function TravelPurposeManager({ initialItems }: { initialItems: AdminCard[] }) {
  const [items, setItems] = useState(initialItems);
  const [draft, setDraft] = useState<AdminCard | JourneyPurposeCard | null>(null);
  const sorted = [...items].sort((a, b) => a.displayOrder - b.displayOrder || a.id - b.id);
  async function reload() { const result = await request<{ items: AdminCard[] }>("/api/admin/journey-purpose"); setItems(result.items); }
  async function remove(item: AdminCard) { if (!window.confirm(`Delete “${item.title}”? This cannot be undone.`)) return; try { await request(`/api/admin/journey-purpose?id=${item.id}`, { method: "DELETE" }); toast.success("Travel purpose card deleted"); await reload(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to delete card."); } }
  async function move(index: number, direction: -1 | 1) { const next = [...sorted]; const target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setItems(next.map((item, itemIndex) => ({ ...item, displayOrder: itemIndex + 1 }))); try { await request("/api/admin/journey-purpose", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ids: next.map((item) => item.id) }) }); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to reorder cards."); await reload(); } }
  return <section><div className="admin-section-head"><div><span>Website content</span><h2>Travel Purpose Cards</h2><p>Manage the cards shown in “Travel with a purpose” on the homepage.</p></div><button className="admin-btn primary" onClick={() => setDraft({ ...emptyCard, displayOrder: sorted.length + 1 })}><Plus />Add card</button></div>{draft && <PurposeCardForm item={draft} onCancel={() => setDraft(null)} onSaved={async () => { setDraft(null); await reload(); }} />}{!sorted.length && <div className="empty-state"><Route /><b>No travel purpose cards yet.</b></div>}<div className="admin-list">{sorted.map((item, index) => { const Icon = icons[item.icon as keyof typeof icons] || Route; return <div className="admin-card" key={item.id}><span className="purpose-card-icon"><Icon /></span><div className="card-main"><div className="badges"><span>{item.linkType === "external" ? "External URL" : "Internal page"}</span><span className={item.active ? "success" : ""}>{item.active ? "Active" : "Inactive"}</span><span>Order {item.displayOrder}</span></div><b>{item.title}</b><p>{item.description}</p><small>{item.destinationUrl} · {item.openInNewTab ? "New tab" : "Same tab"}</small></div><div className="card-actions"><button className="admin-icon-btn" title="Move up" disabled={index === 0} onClick={() => void move(index, -1)}><ChevronUp /></button><button className="admin-icon-btn" title="Move down" disabled={index === sorted.length - 1} onClick={() => void move(index, 1)}><ChevronDown /></button><button className="admin-icon-btn" title="Edit card" onClick={() => setDraft(item)}><Pencil /></button><button className="admin-icon-btn danger" title="Delete card" onClick={() => void remove(item)}><Trash2 /></button></div></div>; })}</div></section>;
}

function PurposeCardForm({ item, onCancel, onSaved }: { item: AdminCard | JourneyPurposeCard; onCancel: () => void; onSaved: () => Promise<void> }) {
  const [linkType, setLinkType] = useState(item.linkType);
  const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const data = new FormData(event.currentTarget); const payload = { id: "id" in item ? item.id : undefined, title: String(data.get("title") || ""), description: String(data.get("description") || ""), icon: String(data.get("icon") || "Route"), buttonText: String(data.get("buttonText") || "Explore journey"), destinationUrl: String(data.get("destinationUrl") || ""), linkType, openInNewTab: data.get("openInNewTab") === "on", displayOrder: Number(data.get("displayOrder") || 0), active: data.get("active") === "on" }; try { await request("/api/admin/journey-purpose", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); toast.success("Travel purpose card saved"); await onSaved(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to save card."); } finally { setSaving(false); } }
  return <form className="admin-editor" onSubmit={submit}><div className="editor-head"><div><span>Travel purpose card</span><h3>{"id" in item ? "Edit card" : "Add card"}</h3><p>Assign a valid internal page or external destination URL.</p></div><button type="button" onClick={onCancel}><X />Cancel</button></div><div className="form-grid two"><label><span>Card title *</span><input name="title" defaultValue={item.title} required /></label><label><span>Icon *</span><select name="icon" defaultValue={item.icon}>{Object.keys(icons).map((icon) => <option key={icon}>{icon}</option>)}</select></label><label className="field-span-2"><span>Description *</span><textarea name="description" defaultValue={item.description} rows={3} required /></label><label><span>Button text *</span><input name="buttonText" defaultValue={item.buttonText} required /></label><label><span>Display order *</span><input name="displayOrder" type="number" min="0" defaultValue={item.displayOrder} required /></label><label><span>Link type *</span><select name="linkType" value={linkType} onChange={(event) => setLinkType(event.target.value as "internal" | "external")}><option value="internal">Internal Page</option><option value="external">External URL</option></select></label><label><span>Destination URL *</span><input name="destinationUrl" defaultValue={item.destinationUrl} placeholder={linkType === "internal" ? "/packages" : "https://example.com"} required /></label></div><div className="editor-footer"><label className="check"><input type="checkbox" name="active" defaultChecked={item.active} /> Active</label><label className="check"><input type="checkbox" name="openInNewTab" defaultChecked={item.openInNewTab} /> Open in new tab</label><button className="admin-btn primary" disabled={saving}><Save />{saving ? "Saving…" : "Save card"}</button><button type="button" className="admin-btn" onClick={onCancel}>Cancel</button></div></form>;
}
