import { asc, eq } from "drizzle-orm";
import { z } from "zod";
import { getDb } from "@/db";
import { journeyPurposeCards } from "@/db/schema";
import { defaultJourneyPurposeCards } from "@/lib/content";
import { requireAdminApi } from "@/lib/admin-auth";

const cardSchema = z.object({ id: z.number().int().positive().optional(), title: z.string().trim().min(2).max(100), description: z.string().trim().min(5).max(300), icon: z.enum(["ShieldCheck", "MapPinned", "Sparkles", "Route", "Headphones", "BadgeCheck"]), buttonText: z.string().trim().min(2).max(40), destinationUrl: z.string().trim().min(1).max(500), linkType: z.enum(["internal", "external"]), openInNewTab: z.boolean(), displayOrder: z.coerce.number().int().min(0), active: z.boolean() }).superRefine((value, context) => { const valid = value.linkType === "internal" ? /^\/(?!\/)/.test(value.destinationUrl) : /^https?:\/\/[^\s]+$/i.test(value.destinationUrl); if (!valid) context.addIssue({ code: z.ZodIssueCode.custom, path: ["destinationUrl"], message: value.linkType === "internal" ? "Use an internal path such as /packages." : "Use a complete http:// or https:// URL." }); });
function values(item: z.infer<typeof cardSchema>) { return { title: item.title, description: item.description, icon: item.icon, buttonText: item.buttonText, destinationUrl: item.destinationUrl, linkType: item.linkType, openInNewTab: item.openInNewTab, displayOrder: item.displayOrder, active: item.active, updatedAt: new Date().toISOString() }; }
async function seedIfEmpty() { const db = getDb(); const rows = await db.select({ id: journeyPurposeCards.id }).from(journeyPurposeCards).limit(1); if (!rows.length) await db.insert(journeyPurposeCards).values(defaultJourneyPurposeCards.map((item) => ({ ...item, updatedAt: new Date().toISOString() }))); }
export async function GET() { const admin = await requireAdminApi(); if (!admin) return Response.json({ error: "Unauthorized" }, { status: 401 }); try { await seedIfEmpty(); return Response.json({ items: await getDb().select().from(journeyPurposeCards).orderBy(asc(journeyPurposeCards.displayOrder), asc(journeyPurposeCards.id)) }); } catch { return Response.json({ items: [] }); } }
export async function POST(request: Request) { const admin = await requireAdminApi(); if (!admin) return Response.json({ error: "Unauthorized" }, { status: 401 }); const parsed = cardSchema.safeParse(await request.json()); if (!parsed.success) return Response.json({ error: parsed.error.issues[0]?.message || "Please complete all card fields." }, { status: 400 }); try { const db = getDb(); const item = parsed.data; if (item.id) { await db.update(journeyPurposeCards).set(values(item)).where(eq(journeyPurposeCards.id, item.id)); return Response.json({ id: item.id }); } const [saved] = await db.insert(journeyPurposeCards).values(values(item)).returning({ id: journeyPurposeCards.id }); return Response.json({ id: saved.id }); } catch { return Response.json({ error: "Unable to save travel purpose card." }, { status: 500 }); } }
export async function PUT(request: Request) { const admin = await requireAdminApi(); if (!admin) return Response.json({ error: "Unauthorized" }, { status: 401 }); const parsed = z.object({ ids: z.array(z.number().int().positive()).min(1) }).safeParse(await request.json()); if (!parsed.success) return Response.json({ error: "Invalid card order." }, { status: 400 }); const db = getDb(); await Promise.all(parsed.data.ids.map((id, index) => db.update(journeyPurposeCards).set({ displayOrder: index + 1, updatedAt: new Date().toISOString() }).where(eq(journeyPurposeCards.id, id)))); return Response.json({ ok: true }); }
export async function DELETE(request: Request) { const admin = await requireAdminApi(); if (!admin) return Response.json({ error: "Unauthorized" }, { status: 401 }); const id = Number(new URL(request.url).searchParams.get("id")); if (!Number.isInteger(id) || id < 1) return Response.json({ error: "Invalid card." }, { status: 400 }); await getDb().delete(journeyPurposeCards).where(eq(journeyPurposeCards.id, id)); return Response.json({ ok: true }); }